"""add offer_type and offer_value to reel_ads

Revision ID: 4cb6b1ea9f59
Revises: bfbe087f1782
Create Date: 2026-02-07 13:58:32.351016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cb6b1ea9f59'
down_revision = 'bfbe087f1782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reel_ads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offer_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('offer_value', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('offer_text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reel_ads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offer_text', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
        batch_op.drop_column('expires_at')
        batch_op.drop_column('offer_value')
        batch_op.drop_column('offer_type')

    # ### end Alembic commands ###
